### ISSUE TITLE
1.19.2与暮色森林冲突

### ISSUE THREAD

**Issue by Arborsm** [Suel-ki/Beautify-Refabricated#1]
单独环境测试，与暮色森林冲突
以下是PCL错误报告
[Uploading 错误报告-2023-1-17_20.58.32.zip…]()

**Comment by Arborsm** [comment]
大概是这些java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'twilightforest'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.ExceptionInInitializerError
	at twilightforest.init.TFBlocks.lambda$static$186(TFBlocks.java:224)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlocks.<clinit>(TFBlocks.java:224)
	at twilightforest.init.TFBlockEntities.lambda$static$0(TFBlockEntities.java:22)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlockEntities.<clinit>(TFBlockEntities.java:21)
	at twilightforest.TwilightForestMod.onInitialize(TwilightForestMod.java:90)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at twilightforest.enums.BossVariant.<clinit>(BossVariant.java:15)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

**Comment by Arborsm** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'twilightforest'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.ExceptionInInitializerError
	at twilightforest.init.TFBlocks.lambda$static$186(TFBlocks.java:224)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlocks.<clinit>(TFBlocks.java:224)
	at twilightforest.init.TFBlockEntities.lambda$static$0(TFBlockEntities.java:22)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlockEntities.<clinit>(TFBlockEntities.java:21)
	at twilightforest.TwilightForestMod.onInitialize(TwilightForestMod.java:90)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at twilightforest.enums.BossVariant.<clinit>(BossVariant.java:15)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
