### ISSUE TITLE
Crash when Supplementaries bombs are thrown

### ISSUE THREAD

**Issue by noiverre** [Suel-ki/Beautify-Refabricated#16]
[13:52:16] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24

1. Install Supplementaries and Beautify
2. Place some Beautify blocks
3. Throw bombs onto it

```
[16:33:31] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[server-intermediary.jar:?]
	at io.github.suel_ki.beautify.common.block.Blinds.sameBlindType(Blinds.java:221) ~[beautify-1.1.0+fabric-1.20.jar:?]
	at io.github.suel_ki.beautify.common.block.Blinds.method_9586(Blinds.java:254) ~[beautify-1.1.0+fabric-1.20.jar:?]
	at net.mehvahdjukaar.moonlight.api.platform.fabric.ForgeHelperImpl.onBlockExploded(ForgeHelperImpl.java:94) ~[moonlight-1.20-2.8.68-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.platform.ForgeHelper.onBlockExploded(ForgeHelper.java) ~[moonlight-1.20-2.8.68-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.misc.explosion.BombExplosion.doFinalizeExplosion(BombExplosion.java:102) ~[supplementaries-1.20-2.7.11-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.entities.BombEntity.createExplosion(BombEntity.java:316) ~[supplementaries-1.20-2.7.11-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.entities.BombEntity.reachedEndOfLife(BombEntity.java:283) ~[supplementaries-1.20-2.7.11-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.entities.BombEntity.method_7488(BombEntity.java:265) ~[supplementaries-1.20-2.7.11-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.entity.ImprovedProjectileEntity.method_5773(ImprovedProjectileEntity.java:220) ~[moonlight-1.20-2.8.68-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.entities.BombEntity.method_5773(BombEntity.java:185) ~[supplementaries-1.20-2.7.11-fabric.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
[16:33:31] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-12-18_16.33.31-server.txt
[16:33:31] [Server thread/INFO]: Scheduling Discord bot presence updates with category 'stopping' for every 60 second(s)
[16:33:31] [Server thread/INFO]: Async Locator -> Shutting down locating executor service
[16:33:31] [Server thread/INFO]: Stored scheduled creeper explosion event(s) to ./world/./scheduled-explosions.json
[16:33:31] [Server thread/INFO]: [STDOUT]: Saving server results
[16:33:31] [Server thread/INFO]: [STDOUT]: Saving config results
[16:33:31] [Server thread/INFO]: Stopping server
[16:33:31] [Server thread/INFO]: Saving players
```

**Comment by Suel-ki** [comment]
It's strange that this issue didn't happen when I tested it, can you provide the full log and mod list?

**Comment by noiverre** [comment]
This is the last few lines before the console logs nothing
```
[06:16:56] [Server thread/INFO]: Overworld OzLynx1514 > tru
[06:17:03] [Server thread/ERROR]: Invalid entity rotation: NaN, discarding.
[06:17:03] [Server thread/ERROR]: Invalid entity rotation: NaN, discarding.
[06:17:03] [Server thread/ERROR]: Invalid entity rotation: NaN, discarding.
[06:17:03] [Server thread/ERROR]: Invalid entity rotation: NaN, discarding.
[06:17:43] [JDA MainWS-ReadThread/INFO]: @frozenriver#0000 > bgst ngelag dc di end
[06:17:51] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[06:17:51] [JDA MainWS-ReadThread/INFO]: @noiverre#0000 > dat
[06:17:52] [JDA MainWS-ReadThread/INFO]: @noiverre#0000 > gw jg lag
[06:17:55] [JDA MainWS-ReadThread/INFO]: @noiverre#0000 > tapi chatnya jalan
[06:18:03] [Server Watchdog/ERROR]: A single server tick took 60.03 seconds (should be max 0.05)
[06:18:03] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[06:18:04] [Server Watchdog/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-12-23_06.18.04-server.txt
```

Here's the crash log, the mod list is in the bottom of that log
https://paste.gg/p/anonymous/c45fc3dfb2344e8b85b6969c6a1e4d98
