### ISSUE TITLE
1.19.2 crashes with Twilight Forest

### ISSUE THREAD

**Issue by TheKaizerWIthin** [Suel-ki/Beautify-Refabricated#4]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'twilightforest'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at twilightforest.init.TFBlocks.lambda$static$186(TFBlocks.java:224)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlocks.<clinit>(TFBlocks.java:224)
	at twilightforest.init.TFBlockEntities.lambda$static$0(TFBlockEntities.java:22)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:60)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:55)
	at twilightforest.init.TFBlockEntities.<clinit>(TFBlockEntities.java:21)
	at twilightforest.TwilightForestMod.onInitialize(TwilightForestMod.java:90)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at twilightforest.enums.BossVariant.<clinit>(BossVariant.java:15)
	... 18 more

**Comment by TheKaizerWIthin** [comment]
removing beautify-refrabricated fixes the issue

**Comment by Suel-ki** [comment]
v1.1.0
